import { Banner } from '@/components/banner';
import { DefaultFooter } from '@/components/footers';
import { AdminHeader, HomeHeader } from '@/components/headers';
import {
  AdminWrapper,
  DefaultWrapper,
  HomeWrapper,
  PageWrapper,
} from '@/components/wrappers';
import {
  Login,
  Logout,
  Home,
  Signup,
  NotFound,
  PrivacyPolicy,
  Mou,
  Advisors,
  Post,
  Founder,
  ChairmanMessage,
  MissionAndHistory,
  OrgchartAndProject,
  Events,
  EventDetail,
  EventRegistration,
  Accelerating,
  ResearchSupportProject,
  Announcement,
  PressRelease,
  Trand,
  Column,
  Photo,
  Sponsorship,
  Benefits,
  SponsorshipHistory,
  SponsorshipApply,
  Sponsors,
  JudgingEventAll,
  JudgingEventDetail,
  JudgingEventRegistration,
  JudgingParticipantAll,
  JudgingResultCreate,
  PrivateEventRegistration,
  AdminUserAll,
  AdminUserPermissionEdit,
  AdminPostAll,
  AdminPostEdit,
  AdminPostUpload,
  AdminBannerAll,
  AdminBannerEdit,
  AdminSponsoringCompanyAll,
  AdminSponsoringCompanyUpload,
  AdminSponsoringCompanyEdit,
  AdminSponsorAll,
  AdminMouAll,
  AdminHistoryUpload,
  AdminMouEdit,
  AdminAdvisorAll,
  AdminAdvisorUpload,
  AdminAdvisorEdit,
  Test,
  AdminBannerUpload,
  AdminPublicEventAll,
  AdminPublicEventUpload,
  AdminPublicEventEdit,
  AdminPublicParticipantAll,
  AdminPublicParticipantEdit,
  AdminPrivateEventAll,
  AdminPrivateEventUpload,
  AdminPrivateEventEdit,
  AdminPrivateParticipantAll,
  AdminPrivateParticipantEdit,
  AdminJudgingEventAll,
  AdminJudgingEventEdit,
  AdminJudgingParticipantAll,
  AdminJudgingParticipantEdit,
  AdminJudgingResultAll,
  AdminJudgingResultDetail,
  AdminAdEmailAll,
  AdminAdEmailUpload,
  AdminHistoryAll,
  AdminHistoryEdit,
  AdminPopupAll,
  AdminPopupUpload,
  AdminPopupEdit,
  Me,
  JudgingParticipantEdit,
  PrivateParticipantEdit,
} from '@/pages';

interface RouteConfig {
  PATH: string;
  COMPONENT: () => JSX.Element;
  HEADER: () => JSX.Element;
  FOOTER?: () => JSX.Element;
  BANNER?: () => JSX.Element;
  WRAPPER: ({
    children,
  }: {
    children: React.ReactNode;
  }) => JSX.Element;
  AUTH: boolean;
  ADMIN?: boolean;
}

type RouteMap = RouteConfig[];

export const ROUTE_MAP: RouteMap = [
  {
    PATH: '/',
    COMPONENT: Home,
    HEADER: HomeHeader,
    BANNER: Banner,
    FOOTER: DefaultFooter,
    WRAPPER: HomeWrapper,
    AUTH: false,
  },
  {
    PATH: '/me',
    COMPONENT: Me,
    HEADER: HomeHeader,
    BANNER: Banner,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/login',
    COMPONENT: Login,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: DefaultWrapper,
    AUTH: false,
  },
  {
    PATH: '/logout',
    COMPONENT: Logout,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: DefaultWrapper,
    AUTH: true,
  },
  {
    PATH: '/signup',
    COMPONENT: Signup,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: DefaultWrapper,
    AUTH: false,
  },
  {
    PATH: '/privacy-policy',
    COMPONENT: PrivacyPolicy,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/mou',
    COMPONENT: Mou,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/advisors',
    COMPONENT: Advisors,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/post/:id',
    COMPONENT: Post,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/introduction',
    COMPONENT: Founder,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/introduction/founder',
    COMPONENT: Founder,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/introduction/message',
    COMPONENT: ChairmanMessage,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/introduction/mission_and_history',
    COMPONENT: MissionAndHistory,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/introduction/orgchart_and_project',
    COMPONENT: OrgchartAndProject,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs',
    COMPONENT: Events,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/event',
    COMPONENT: Events,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/event/:id/detail',
    COMPONENT: EventDetail,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/event/:id/registration',
    COMPONENT: EventRegistration,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/accelerating',
    COMPONENT: Accelerating,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/research_support_project',
    COMPONENT: ResearchSupportProject,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/programs/trand',
    COMPONENT: Trand,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/news',
    COMPONENT: Announcement,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/news/announcement',
    COMPONENT: Announcement,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/news/press_release',
    COMPONENT: PressRelease,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/news/column',
    COMPONENT: Column,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/news/photo',
    COMPONENT: Photo,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support',
    COMPONENT: Sponsorship,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support/sponsorship',
    COMPONENT: Sponsorship,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support/benefits',
    COMPONENT: Benefits,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support/sponsors',
    COMPONENT: Sponsors,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support/history',
    COMPONENT: SponsorshipHistory,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
  {
    PATH: '/support/sponsorship/apply',
    COMPONENT: SponsorshipApply,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/event/all',
    COMPONENT: JudgingEventAll,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/event/:event_id/detail',
    COMPONENT: JudgingEventDetail,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/event/:event_id/registration',
    COMPONENT: JudgingEventRegistration,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/participant/edit/:id',
    COMPONENT: JudgingParticipantEdit,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/result/:event_id/all',
    COMPONENT: JudgingParticipantAll,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/result/:event_id/:participant_id/:nth/create',
    COMPONENT: JudgingResultCreate,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/judging/result/:event_id/:participant_id/:nth/create',
    COMPONENT: JudgingResultCreate,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/private_event/:id/registration',
    COMPONENT: PrivateEventRegistration,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/private_event/participant/edit/:id',
    COMPONENT: PrivateParticipantEdit,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: true,
  },
  {
    PATH: '/admin',
    COMPONENT: AdminUserAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/user/all',
    COMPONENT: AdminUserAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/user/permission/edit/:id',
    COMPONENT: AdminUserPermissionEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/post/all',
    COMPONENT: AdminPostAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/post/upload',
    COMPONENT: AdminPostUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/post/edit/:id',
    COMPONENT: AdminPostEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/banner',
    COMPONENT: AdminBannerAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/banner/all',
    COMPONENT: AdminBannerAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/banner/upload',
    COMPONENT: AdminBannerUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/banner/edit/:id',
    COMPONENT: AdminBannerEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/sponsoring_company/all',
    COMPONENT: AdminSponsoringCompanyAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/sponsoring_company/upload',
    COMPONENT: AdminSponsoringCompanyUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/sponsoring_company/edit/:id',
    COMPONENT: AdminSponsoringCompanyEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/sponsor/all',
    COMPONENT: AdminSponsorAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/mou/all',
    COMPONENT: AdminMouAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/mou/upload',
    COMPONENT: AdminHistoryUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/mou/edit/:id',
    COMPONENT: AdminMouEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/advisor/all',
    COMPONENT: AdminAdvisorAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/advisor/upload',
    COMPONENT: AdminAdvisorUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/advisor/edit/:id',
    COMPONENT: AdminAdvisorEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_event',
    COMPONENT: AdminPublicEventAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_event/all',
    COMPONENT: AdminPublicEventAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_event/upload',
    COMPONENT: AdminPublicEventUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_event/edit/:id',
    COMPONENT: AdminPublicEventEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_participant',
    COMPONENT: AdminPublicParticipantAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_participant/all',
    COMPONENT: AdminPublicParticipantAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/public_participant/edit/:id',
    COMPONENT: AdminPublicParticipantEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/private_event',
    COMPONENT: AdminPrivateEventAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/private_event/all',
    COMPONENT: AdminPrivateEventAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/private_event/upload',
    COMPONENT: AdminPrivateEventUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/private_event/edit/:id',
    COMPONENT: AdminPrivateEventEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/private_participant/all',
    COMPONENT: AdminPrivateParticipantAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_event/all',
    COMPONENT: AdminJudgingEventAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_event/upload',
    COMPONENT: AdminJudgingEventEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_event/edit/:id',
    COMPONENT: AdminJudgingEventEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_participant',
    COMPONENT: AdminJudgingParticipantAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_participant/all',
    COMPONENT: AdminJudgingParticipantAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_participant/detail/:id',
    COMPONENT: AdminJudgingParticipantEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_result/all',
    COMPONENT: AdminJudgingResultAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/judging_result/detail/:id',
    COMPONENT: AdminJudgingResultDetail,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/ad_email',
    COMPONENT: AdminAdEmailAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/ad_email/all',
    COMPONENT: AdminAdEmailAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/ad_email/upload',
    COMPONENT: AdminAdEmailUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/history',
    COMPONENT: AdminHistoryAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/history/all',
    COMPONENT: AdminHistoryAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/history/upload',
    COMPONENT: AdminHistoryUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/history/edit/:id',
    COMPONENT: AdminHistoryEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/popup/all',
    COMPONENT: AdminPopupAll,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/popup/upload',
    COMPONENT: AdminPopupUpload,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/admin/popup/edit/:id',
    COMPONENT: AdminPopupEdit,
    HEADER: AdminHeader,
    WRAPPER: AdminWrapper,
    ADMIN: true,
    AUTH: true,
  },
  {
    PATH: '/Test',
    COMPONENT: Test,
    HEADER: () => {
      return <></>;
    },
    FOOTER: () => {
      return <></>;
    },
    WRAPPER: ({ children }) => {
      return <>{children}</>;
    },
    AUTH: false,
  },
  {
    PATH: '*',
    COMPONENT: NotFound,
    HEADER: HomeHeader,
    FOOTER: DefaultFooter,
    WRAPPER: PageWrapper,
    AUTH: false,
  },
];
