"""empty message

Revision ID: 37b1ab945313
Revises: 33ef405057a3
Create Date: 2023-03-05 22:05:35.521040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b1ab945313'
down_revision = '33ef405057a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=200), nullable=False, comment='팝업 제목'))
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=300), nullable=False, comment='팝업 이미지 파일명'))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=300), nullable=False, comment='팝업 링크'))
        batch_op.add_column(sa.Column('popup_start_date', sa.DATE(), nullable=False, comment='팝업 표시 시작 날짜'))
        batch_op.add_column(sa.Column('popup_end_date', sa.DATE(), nullable=False, comment='팝업 표시 종료 날짜'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시점'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시점'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('startup_investing_forum_participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'startup_investing_forum_event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_investing_forum_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('popup', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('popup_end_date')
        batch_op.drop_column('popup_start_date')
        batch_op.drop_column('link')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('title')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
