"""empty message

Revision ID: 3c9e485f80ab
Revises: 3c83f58a245e
Create Date: 2023-02-24 19:00:50.233833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c9e485f80ab'
down_revision = '3c83f58a245e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_event',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False, comment='참가자 고유 번호'),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False, comment='행사 이름 (한글)'),
    sa.Column('english_name', sa.VARCHAR(length=100), nullable=True, comment='행사 이름 (영문)'),
    sa.Column('description', sa.VARCHAR(length=2000), nullable=False, comment='행사 설명'),
    sa.Column('start_date', sa.DATE(), nullable=False, comment='행사 시작 날짜'),
    sa.Column('end_date', sa.DATE(), nullable=False, comment='행사 종료 날짜'),
    sa.Column('join_start_date', sa.DATE(), nullable=False, comment='참가 신청 시작 날짜'),
    sa.Column('join_end_date', sa.DATE(), nullable=False, comment='참가 신청 종료 날짜'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시점'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시점'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_collate='utf8_general_ci'
    )
    op.create_table('participant',
    sa.Column('id', mysql.INTEGER(unsigned=True), nullable=False, comment='참가자 고유 번호'),
    sa.Column('public_event_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False, comment='참가자 이름 (한글)'),
    sa.Column('english_name', sa.VARCHAR(length=100), nullable=True, comment='참가자 이름 (영문)'),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=False, comment='참가자 성별'),
    sa.Column('birth', sa.DATE(), nullable=False, comment='참가자 생년월일'),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False, comment='참가자 연락처'),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False, comment='참가자 이메일'),
    sa.Column('organization_type', sa.VARCHAR(length=100), nullable=False, comment='참가자 소속 분류'),
    sa.Column('organization_name', sa.VARCHAR(length=100), nullable=False, comment='참가자 소속기관명'),
    sa.Column('organization_english_name', sa.VARCHAR(length=100), nullable=True, comment='참가자 소속기관명 (영문)'),
    sa.Column('job_position', sa.VARCHAR(length=100), nullable=False, comment='참가자 직위'),
    sa.Column('address', sa.VARCHAR(length=100), nullable=False, comment='참가자 소재지'),
    sa.Column('final_degree', sa.VARCHAR(length=100), nullable=False, comment='참가자 최종 학력'),
    sa.Column('engagement_type', sa.VARCHAR(length=100), nullable=False, comment='참가자 참여유형'),
    sa.Column('participant_motivation', sa.VARCHAR(length=100), nullable=False, comment='참가자 참여동기'),
    sa.Column('participant_type', sa.VARCHAR(length=100), nullable=False, comment='참가자 유형'),
    sa.Column('interest_disease', sa.VARCHAR(length=100), nullable=False, comment='참가자 관심 질환'),
    sa.Column('interest_field', sa.VARCHAR(length=20), nullable=False, comment='참가자 관심 분야'),
    sa.Column('interest_field_detail', sa.VARCHAR(length=100), nullable=False, comment='참가자 관심 분야 상세'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시점'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시점'),
    sa.ForeignKeyConstraint(['public_event_id'], ['public_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_collate='utf8_general_ci'
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('participant')
    op.drop_table('public_event')
    # ### end Alembic commands ###
