"""empty message

Revision ID: 591957f2a4c5
Revises: 648d516b0a56
Create Date: 2023-03-05 20:10:08.995221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '591957f2a4c5'
down_revision = '648d516b0a56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('startup_investing_forum_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resident_registration_number', sa.VARCHAR(length=13), nullable=True, comment='참가자 주민등록번호'))
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment=None,
               existing_comment='스타트업 투자 포럼 고유 번호',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'startup_investing_forum_event', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('startup_investing_forum_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('event_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='스타트업 투자 포럼 고유 번호',
               existing_nullable=True)
        batch_op.drop_column('resident_registration_number')

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
