"""rename table advisor_group to advisor

Revision ID: 62dbea6ee78a
Revises: f420cb6e5402
Create Date: 2023-02-11 02:27:29.658046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62dbea6ee78a'
down_revision = 'f420cb6e5402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor',
    sa.Column('id', sa.Integer(), nullable=False, comment='자문단 고유 번호'),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False, comment='자문단 위원 이름'),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False, comment='자문단 위원 설명'),
    sa.Column('filename', sa.VARCHAR(length=40), nullable=False, comment='이미지 파일명'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시점'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시점'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    mysql_collate='utf8_general_ci'
    )
    with op.batch_alter_table('advisor_group', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('advisor_group')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('advisor_group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='자문단 고유 번호'),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False, comment='자문단 위원 이름'),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=False, comment='자문단 위원 설명'),
    sa.Column('filename', mysql.VARCHAR(length=40), nullable=False, comment='이미지 파일명'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='생성 시점'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='마지막 수정 시점'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('advisor_group', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    op.drop_table('advisor')
    # ### end Alembic commands ###
