"""empty message

Revision ID: 648d516b0a56
Revises: 8cbf35b7eeaa
Create Date: 2023-03-03 09:38:38.241437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '648d516b0a56'
down_revision = '8cbf35b7eeaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('supporting_startup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False, comment='스타트업 이름'))
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=100), nullable=False, comment='홈페이지 링크'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='지원 중인 스타트업 고유 번호',
               existing_comment='연혁 고유 번호',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=3000),
               comment='스타트업 내용',
               existing_comment='연혁 내용',
               existing_nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supporting_startup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=100), nullable=False, comment='연혁 제목'))
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=3000),
               comment='연혁 내용',
               existing_comment='스타트업 내용',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='연혁 고유 번호',
               existing_comment='지원 중인 스타트업 고유 번호',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('link')
        batch_op.drop_column('name')

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
