"""migration message

Revision ID: 752293db95b0
Revises: 92607afbe55b
Create Date: 2023-06-25 15:36:34.503506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '752293db95b0'
down_revision = '92607afbe55b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('untitled_table_21', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('untitled_table_21')
    with op.batch_alter_table('judging_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nth_pass', mysql.INTEGER(unsigned=True), nullable=False, comment='n차 심사 중'))
        batch_op.create_foreign_key(None, 'judging_event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('judging_permission', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'judging_event', ['judging_event_id'], ['id'])

    with op.batch_alter_table('judging_result', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'judging_event', ['judging_event_id'], ['id'])
        batch_op.create_foreign_key(None, 'judging_participant', ['participant_id'], ['id'])

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'private_event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('judging_result', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('judging_permission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('judging_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nth_pass')

    op.create_table('untitled_table_21',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('untitled_table_21', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=False)

    # ### end Alembic commands ###
