"""empty message

Revision ID: ac3b02974c65
Revises: e157e21568a0
Create Date: 2023-02-27 19:12:51.541533

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac3b02974c65'
down_revision = 'e157e21568a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_eamil', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=True, comment='사용자 고유 번호'))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=200), nullable=False, comment='이메일'))
        batch_op.add_column(sa.Column('subscribe', sa.BOOLEAN(), nullable=False, comment='구독 여부'))
        batch_op.add_column(sa.Column('etc_info', sa.VARCHAR(length=100), nullable=True, comment='기타 정보'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 시점'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='마지막 수정 시점'))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='이메일 고유 번호',
               existing_comment='참가자 고유 번호',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('ad_eamil', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='참가자 고유 번호',
               existing_comment='이메일 고유 번호',
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('etc_info')
        batch_op.drop_column('subscribe')
        batch_op.drop_column('email')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
