"""empty message

Revision ID: bf8736149de7
Revises: e1dd03f3aea2
Create Date: 2023-04-16 23:02:02.250353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf8736149de7'
down_revision = 'e1dd03f3aea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('private_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_start_date', sa.DATE(), nullable=False, comment='참가 신청 시작 날짜'))
        batch_op.add_column(sa.Column('join_end_date', sa.DATE(), nullable=False, comment='참가 신청 종료 날짜'))
        batch_op.drop_column('year')

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'private_event', ['event_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('private_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='연도'))
        batch_op.drop_column('join_end_date')
        batch_op.drop_column('join_start_date')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
