"""empty message

Revision ID: c9a6100bbe92
Revises: 
Create Date: 2023-01-16 22:22:08.810293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a6100bbe92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(),
                  server_default='01000000000', nullable=True, comment='전화번호'))
    op.add_column('user', sa.Column('birth', sa.String(),
                  server_default='1900-01-01', nullable=False, comment='생년월일'))
    op.add_column('user', sa.Column('email_enable', sa.BOOLEAN(),
                  server_default='t', nullable=False, comment='이메일 수신 여부'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'email_enable')
    op.drop_column('user', 'birth')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
