"""empty message

Revision ID: e157e21568a0
Revises: 3c9e485f80ab
Create Date: 2023-02-26 01:19:08.333059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e157e21568a0'
down_revision = '3c9e485f80ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True,
               existing_comment='참가자 성별')
        batch_op.alter_column('birth',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='참가자 생년월일')
        batch_op.alter_column('organization_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 소속 분류')
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 소재지')
        batch_op.alter_column('final_degree',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 최종 학력')
        batch_op.alter_column('engagement_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 참여유형')
        batch_op.alter_column('participant_motivation',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 참여동기')
        batch_op.alter_column('participant_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 유형')
        batch_op.alter_column('interest_disease',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 관심 질환')
        batch_op.alter_column('interest_field',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_comment='참가자 관심 분야')
        batch_op.alter_column('interest_field_detail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='참가자 관심 분야 상세')
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('interest_field_detail',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 관심 분야 상세')
        batch_op.alter_column('interest_field',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_comment='참가자 관심 분야')
        batch_op.alter_column('interest_disease',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 관심 질환')
        batch_op.alter_column('participant_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 유형')
        batch_op.alter_column('participant_motivation',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 참여동기')
        batch_op.alter_column('engagement_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 참여유형')
        batch_op.alter_column('final_degree',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 최종 학력')
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 소재지')
        batch_op.alter_column('organization_type',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='참가자 소속 분류')
        batch_op.alter_column('birth',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='참가자 생년월일')
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False,
               existing_comment='참가자 성별')

    # ### end Alembic commands ###
