"""migration message

Revision ID: e1dd03f3aea2
Revises: 3634d50a2cbf
Create Date: 2023-04-16 22:19:53.171452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1dd03f3aea2'
down_revision = '3634d50a2cbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'public_event', ['public_event_id'], ['id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])

    with op.batch_alter_table('private_event', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='고유 번호',
               existing_comment='스타트업 투자 포럼 고유 번호',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               comment='이름',
               existing_comment='스타트업 투자 포럼 이름',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='연도',
               existing_comment='스타트업 투자 포럼 연도',
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=3000),
               comment='설명',
               existing_comment='스타트업 투자 포럼 설명',
               existing_nullable=False)

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='참가자 고유 번호',
               existing_comment='스타트업 투자 포럼 참가자 고유 번호',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='참가자 고유 번호',
               existing_comment='스타트업 투자 포럼 참가자 고유 번호',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'private_event', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('private_participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='스타트업 투자 포럼 참가자 고유 번호',
               existing_comment='참가자 고유 번호',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='스타트업 투자 포럼 참가자 고유 번호',
               existing_comment='참가자 고유 번호',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('private_event', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=3000),
               comment='스타트업 투자 포럼 설명',
               existing_comment='설명',
               existing_nullable=False)
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='스타트업 투자 포럼 연도',
               existing_comment='연도',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=200),
               comment='스타트업 투자 포럼 이름',
               existing_comment='이름',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(display_width=10, unsigned=True),
               comment='스타트업 투자 포럼 고유 번호',
               existing_comment='고유 번호',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
