"""add advisor_group table

Revision ID: f420cb6e5402
Revises: b78c809156f7
Create Date: 2023-02-11 02:17:15.556048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f420cb6e5402'
down_revision = 'b78c809156f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_group',
                    sa.Column('id', sa.Integer(), nullable=False,
                              comment='자문단 고유 번호'),
                    sa.Column('name', sa.VARCHAR(length=30),
                              nullable=False, comment='자문단 위원 이름'),
                    sa.Column('description', sa.VARCHAR(length=500),
                              nullable=False, comment='자문단 위원 설명'),
                    sa.Column('filename', sa.VARCHAR(length=40),
                              nullable=False, comment='이미지 파일명'),
                    sa.Column('created_at', sa.DateTime(),
                              nullable=False, comment='생성 시점'),
                    sa.Column('updated_at', sa.DateTime(),
                              nullable=False, comment='마지막 수정 시점'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    mysql_collate='utf8_general_ci'
                    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['author_name'], ['name'])
        batch_op.create_foreign_key(None, 'board', ['board_id'], ['id'])

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('sponsoring_company', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsoring_company', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('sponsor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('advisor_group')
    # ### end Alembic commands ###
