import os

DATABASE_URL = os.environ.get("DATABASE_URL")
JWT_PRIVATE_KEY = os.environ.get("JWT_PRIVATE_KEY")
JWT_PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRES_IN = 15
REFRESH_TOKEN_EXPIRES_IN = 60
AWS_ACCESS_KEY_ID = os.environ.get("AWS__ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS__SECRET_ACCESS_KEY")
AWS_S3_BUCKET_NAME = os.environ.get("AWS__S3_BUCKET_NAME")
