import os

DATABASE_URL = os.environ.get("DATABASE_URL")
JWT_PRIVATE_KEY = os.environ.get("JWT_PRIVATE_KEY")
JWT_PUBLIC_KEY = os.environ.get("JWT_PUBLIC_KEY")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRES_IN = 15
REFRESH_TOKEN_EXPIRES_IN = 60
