import os

DATABASE_URL = os.environ.get("DATABASE_URL")
JWT_SECRET_KEY = os.environ.get("JWT_SECRET_KEY")
JWT_ALGORITHM = os.environ.get("JWT_ALGORITHM")
ACCESS_TOKEN_EXPIRES_IN = 15
ACCESS_TOKEN_EXPIRES_IN = 180
REFRESH_TOKEN_EXPIRES_IN = 600
AWS_ACCESS_KEY_ID = os.environ.get("AWS__ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS__SECRET_ACCESS_KEY")
AWS_S3_BUCKET_NAME = os.environ.get("AWS__S3_BUCKET_NAME")
MAIL_SENDER = os.environ.get("MAIL_SENDER")
MAIL_PASSWARD = os.environ.get("MAIL_PASSWARD")
ADMIN_ACCOUNT_ID = os.environ.get("ADMIN_ACCOUNT_ID")
ADMIN_ACCOUNT_PASSWORD = os.environ.get("ADMIN_ACCOUNT_PASSWORD")
API_URL = os.environ.get("API_URL")
