name: Backend CI/CD

on:
  push:
    branches:
      - main
    path:
      - Backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect repository
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: medical-innovation
          yaml: |-
            name: medical-innovation
            app: python@3.9
            options:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
              port: 8000
              nodeversion: 18
              
              intstall: pip install -r requirements.txt
              build: pip install -r requiremants.txt
              start: uvicorn app.main:app --host=0.0.0.0 
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
                path: /Backend
