name: Backend

on:
  push:
    branches: ["main"]
    paths:
      - "Backend/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prev Container Stop
        run: |
          docker stop ${{ secrets.DOCKERHUB_PROJECT_NAME }} && docker rm ${{ secrets.DOCKERHUB_PROJECT_NAME }} && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest

      - name: Container Run
        run: |
          docker run -d --name ${{ secrets.DOCKERHUB_PROJECT_NAME }} -p 443:8000 \
          -v /:/host \
          -e AWS__ACCESS_KEY_ID=${{ secrets.AWS__ACCESS_KEY_ID }} \
          -e AWS__S3_BUCKET_NAME=${{ secrets.AWS__S3_BUCKET_NAME }} \
          -e AWS__SECRET_ACCESS_KEY=${{ secrets.AWS__SECRET_ACCESS_KEY }} \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e JWT_ALGORITHM=${{ secrets.JWT_ALGORITHM }} \
          -e JWT_PRIVATE_KEY=${{ secrets.JWT_PRIVATE_KEY }} \
          -e JWT_PUBLIC_KEY=${{ secrets.JWT_PUBLIC_KEY }} \
          -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          -e MAIL_SENDER=${{ secrets.MAIL_SENDER }} \
          -e MAIL_PASSWARD=${{ secrets.MAIL_PASSWARD }} \
          --restart always ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PROJECT_NAME }}:latest
